// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.0
// source: docs/docs.proto

package docs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocOrRowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*DocOrRowRequest_Doc
	//	*DocOrRowRequest_Row
	Msg isDocOrRowRequest_Msg `protobuf_oneof:"msg"`
}

func (x *DocOrRowRequest) Reset() {
	*x = DocOrRowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_docs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocOrRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocOrRowRequest) ProtoMessage() {}

func (x *DocOrRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_docs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocOrRowRequest.ProtoReflect.Descriptor instead.
func (*DocOrRowRequest) Descriptor() ([]byte, []int) {
	return file_docs_docs_proto_rawDescGZIP(), []int{0}
}

func (m *DocOrRowRequest) GetMsg() isDocOrRowRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *DocOrRowRequest) GetDoc() *DocStreamRequest {
	if x, ok := x.GetMsg().(*DocOrRowRequest_Doc); ok {
		return x.Doc
	}
	return nil
}

func (x *DocOrRowRequest) GetRow() *Row {
	if x, ok := x.GetMsg().(*DocOrRowRequest_Row); ok {
		return x.Row
	}
	return nil
}

type isDocOrRowRequest_Msg interface {
	isDocOrRowRequest_Msg()
}

type DocOrRowRequest_Doc struct {
	Doc *DocStreamRequest `protobuf:"bytes,1,opt,name=doc,proto3,oneof"`
}

type DocOrRowRequest_Row struct {
	Row *Row `protobuf:"bytes,2,opt,name=row,proto3,oneof"`
}

func (*DocOrRowRequest_Doc) isDocOrRowRequest_Msg() {}

func (*DocOrRowRequest_Row) isDocOrRowRequest_Msg() {}

type DocStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows             []*Row `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	SupplyId         int64  `protobuf:"varint,2,opt,name=supply_id,json=supplyId,proto3" json:"supply_id,omitempty"`
	SellerId         int64  `protobuf:"varint,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	ShelfLife        string `protobuf:"bytes,4,opt,name=shelf_life,json=shelfLife,proto3" json:"shelf_life,omitempty"`
	IdempotencyToken string `protobuf:"bytes,5,opt,name=idempotency_token,json=idempotencyToken,proto3" json:"idempotency_token,omitempty"`
	Address          string `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Tin              string `protobuf:"bytes,7,opt,name=tin,proto3" json:"tin,omitempty"`
	Flag             bool   `protobuf:"varint,8,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *DocStreamRequest) Reset() {
	*x = DocStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_docs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocStreamRequest) ProtoMessage() {}

func (x *DocStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_docs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocStreamRequest.ProtoReflect.Descriptor instead.
func (*DocStreamRequest) Descriptor() ([]byte, []int) {
	return file_docs_docs_proto_rawDescGZIP(), []int{1}
}

func (x *DocStreamRequest) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *DocStreamRequest) GetSupplyId() int64 {
	if x != nil {
		return x.SupplyId
	}
	return 0
}

func (x *DocStreamRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *DocStreamRequest) GetShelfLife() string {
	if x != nil {
		return x.ShelfLife
	}
	return ""
}

func (x *DocStreamRequest) GetIdempotencyToken() string {
	if x != nil {
		return x.IdempotencyToken
	}
	return ""
}

func (x *DocStreamRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DocStreamRequest) GetTin() string {
	if x != nil {
		return x.Tin
	}
	return ""
}

func (x *DocStreamRequest) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sku     int64   `protobuf:"varint,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Char    string  `protobuf:"bytes,3,opt,name=char,proto3" json:"char,omitempty"`
	Quality int64   `protobuf:"varint,4,opt,name=quality,proto3" json:"quality,omitempty"`
	AddName string  `protobuf:"bytes,5,opt,name=add_name,json=addName,proto3" json:"add_name,omitempty"`
	AddCode string  `protobuf:"bytes,6,opt,name=add_code,json=addCode,proto3" json:"add_code,omitempty"`
	Count   float64 `protobuf:"fixed64,7,opt,name=count,proto3" json:"count,omitempty"`
	Price   float64 `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	Total   float64 `protobuf:"fixed64,9,opt,name=total,proto3" json:"total,omitempty"`
	Bar     string  `protobuf:"bytes,10,opt,name=bar,proto3" json:"bar,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_docs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_docs_docs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_docs_docs_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Row) GetSku() int64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *Row) GetChar() string {
	if x != nil {
		return x.Char
	}
	return ""
}

func (x *Row) GetQuality() int64 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *Row) GetAddName() string {
	if x != nil {
		return x.AddName
	}
	return ""
}

func (x *Row) GetAddCode() string {
	if x != nil {
		return x.AddCode
	}
	return ""
}

func (x *Row) GetCount() float64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Row) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Row) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Row) GetBar() string {
	if x != nil {
		return x.Bar
	}
	return ""
}

type SendDocResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotarRowsCount int64 `protobuf:"varint,1,opt,name=totar_rows_count,json=totarRowsCount,proto3" json:"totar_rows_count,omitempty"`
}

func (x *SendDocResponse) Reset() {
	*x = SendDocResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_docs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDocResponse) ProtoMessage() {}

func (x *SendDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_docs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDocResponse.ProtoReflect.Descriptor instead.
func (*SendDocResponse) Descriptor() ([]byte, []int) {
	return file_docs_docs_proto_rawDescGZIP(), []int{3}
}

func (x *SendDocResponse) GetTotarRowsCount() int64 {
	if x != nil {
		return x.TotarRowsCount
	}
	return 0
}

var File_docs_docs_proto protoreflect.FileDescriptor

var file_docs_docs_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x6f, 0x63, 0x73, 0x2f, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x22, 0x63, 0x0a, 0x0f, 0x44, 0x6f, 0x63, 0x4f, 0x72,
	0x52, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x03, 0x64, 0x6f,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x44,
	0x6f, 0x63, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x03, 0x64, 0x6f, 0x63, 0x12, 0x1d, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x52, 0x6f, 0x77, 0x48, 0x00,
	0x52, 0x03, 0x72, 0x6f, 0x77, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xf7, 0x01, 0x0a,
	0x10, 0x44, 0x6f, 0x63, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68,
	0x65, 0x6c, 0x66, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x68, 0x65, 0x6c, 0x66, 0x4c, 0x69, 0x66, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x69, 0x64, 0x65,
	0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74,
	0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0xe3, 0x01, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x73, 0x6b, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x68, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6c,
	0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69,
	0x74, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x64, 0x64, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x61,
	0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x61, 0x72, 0x22, 0x3b, 0x0a, 0x0f,
	0x53, 0x65, 0x6e, 0x64, 0x44, 0x6f, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x10, 0x74, 0x6f, 0x74, 0x61, 0x72, 0x5f, 0x72, 0x6f, 0x77, 0x73, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x72,
	0x52, 0x6f, 0x77, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x8d, 0x01, 0x0a, 0x04, 0x44, 0x6f,
	0x63, 0x73, 0x12, 0x40, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x6f, 0x63, 0x46, 0x75, 0x6c,
	0x6c, 0x12, 0x16, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x44, 0x6f, 0x63, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x64, 0x6f, 0x63, 0x73,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x6f, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x12, 0x43, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x6f, 0x63, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x64, 0x69, 0x63, 0x12, 0x15, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x44,
	0x6f, 0x63, 0x4f, 0x72, 0x52, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x6f, 0x63, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2f, 0x64, 0x6f, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_docs_docs_proto_rawDescOnce sync.Once
	file_docs_docs_proto_rawDescData = file_docs_docs_proto_rawDesc
)

func file_docs_docs_proto_rawDescGZIP() []byte {
	file_docs_docs_proto_rawDescOnce.Do(func() {
		file_docs_docs_proto_rawDescData = protoimpl.X.CompressGZIP(file_docs_docs_proto_rawDescData)
	})
	return file_docs_docs_proto_rawDescData
}

var file_docs_docs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_docs_docs_proto_goTypes = []interface{}{
	(*DocOrRowRequest)(nil),  // 0: docs.DocOrRowRequest
	(*DocStreamRequest)(nil), // 1: docs.DocStreamRequest
	(*Row)(nil),              // 2: docs.Row
	(*SendDocResponse)(nil),  // 3: docs.SendDocResponse
}
var file_docs_docs_proto_depIdxs = []int32{
	1, // 0: docs.DocOrRowRequest.doc:type_name -> docs.DocStreamRequest
	2, // 1: docs.DocOrRowRequest.row:type_name -> docs.Row
	2, // 2: docs.DocStreamRequest.rows:type_name -> docs.Row
	1, // 3: docs.Docs.SendDocFull:input_type -> docs.DocStreamRequest
	0, // 4: docs.Docs.SendDocVariadic:input_type -> docs.DocOrRowRequest
	3, // 5: docs.Docs.SendDocFull:output_type -> docs.SendDocResponse
	3, // 6: docs.Docs.SendDocVariadic:output_type -> docs.SendDocResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_docs_docs_proto_init() }
func file_docs_docs_proto_init() {
	if File_docs_docs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_docs_docs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocOrRowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_docs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_docs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_docs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDocResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_docs_docs_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DocOrRowRequest_Doc)(nil),
		(*DocOrRowRequest_Row)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_docs_docs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_docs_proto_goTypes,
		DependencyIndexes: file_docs_docs_proto_depIdxs,
		MessageInfos:      file_docs_docs_proto_msgTypes,
	}.Build()
	File_docs_docs_proto = out.File
	file_docs_docs_proto_rawDesc = nil
	file_docs_docs_proto_goTypes = nil
	file_docs_docs_proto_depIdxs = nil
}
